[build]
  base = "site"
  command = "npm run build"
  publish = "site/public"

[[redirects]]
  from = "/2019/01/welcome-to-vexation*"
  to = "/welcome/"

[[redirects]]
  from = "/2019/01/getting-set-up*"
  to = "/setup/"

[[redirects]]
  from = "/2019/01/pe-file-infector-basics*"
  to = "/pe-infector-basics/"

[[redirects]]
  from = "/2019/03/a-vxers-best-friend-delta-offset*"
  to = "/delta-offset"

[[redirects]]
  from = "/2019/04/using-win95-kernel32dll-exports-like*"
  to = "/kernel32-dll-exports"
